<a href="https://colab.research.google.com/github/19PA1A0465/AI-LAB/blob/master/ADA_Boost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **ADA boost model**

In [0]:
# importimg required libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [218]:
# reading data
ipl=pd.read_csv("Iris.csv")
ipl

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [219]:
ipl.isna().any() # to find NA's

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [220]:
#converting catorical feature to numerical feature
ipl['Species'].replace(to_replace=['Iris-setosa','Iris-versicolor','Iris-virginica'], value=[0,1,2],inplace=True)
ipl.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [221]:
# declaring featuresa and target variable
X = ipl[['SepalWidthCm','PetalLengthCm','PetalWidthCm','SepalLengthCm']].values
y= ipl['Species'].values
print('X=',X)
print('y=',y)

X= [[3.5 1.4 0.2 5.1]
 [3.  1.4 0.2 4.9]
 [3.2 1.3 0.2 4.7]
 [3.1 1.5 0.2 4.6]
 [3.6 1.4 0.2 5. ]
 [3.9 1.7 0.4 5.4]
 [3.4 1.4 0.3 4.6]
 [3.4 1.5 0.2 5. ]
 [2.9 1.4 0.2 4.4]
 [3.1 1.5 0.1 4.9]
 [3.7 1.5 0.2 5.4]
 [3.4 1.6 0.2 4.8]
 [3.  1.4 0.1 4.8]
 [3.  1.1 0.1 4.3]
 [4.  1.2 0.2 5.8]
 [4.4 1.5 0.4 5.7]
 [3.9 1.3 0.4 5.4]
 [3.5 1.4 0.3 5.1]
 [3.8 1.7 0.3 5.7]
 [3.8 1.5 0.3 5.1]
 [3.4 1.7 0.2 5.4]
 [3.7 1.5 0.4 5.1]
 [3.6 1.  0.2 4.6]
 [3.3 1.7 0.5 5.1]
 [3.4 1.9 0.2 4.8]
 [3.  1.6 0.2 5. ]
 [3.4 1.6 0.4 5. ]
 [3.5 1.5 0.2 5.2]
 [3.4 1.4 0.2 5.2]
 [3.2 1.6 0.2 4.7]
 [3.1 1.6 0.2 4.8]
 [3.4 1.5 0.4 5.4]
 [4.1 1.5 0.1 5.2]
 [4.2 1.4 0.2 5.5]
 [3.1 1.5 0.1 4.9]
 [3.2 1.2 0.2 5. ]
 [3.5 1.3 0.2 5.5]
 [3.1 1.5 0.1 4.9]
 [3.  1.3 0.2 4.4]
 [3.4 1.5 0.2 5.1]
 [3.5 1.3 0.3 5. ]
 [2.3 1.3 0.3 4.5]
 [3.2 1.3 0.2 4.4]
 [3.5 1.6 0.6 5. ]
 [3.8 1.9 0.4 5.1]
 [3.  1.4 0.3 4.8]
 [3.8 1.6 0.2 5.1]
 [3.2 1.4 0.2 4.6]
 [3.7 1.5 0.2 5.3]
 [3.3 1.4 0.2 5. ]
 [3.2 4.7 1.4 7. ]
 [3.2 4.5 1.5 6.4]
 [3.1 4.9

In [0]:
# splitting of data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, z, test_size=0.3,random_state=143)

In [223]:
print("X_train",X_train)
print("X_test",X_test)

print("y_train",y_train)
print("y_test",y_test)

X_train [[3.  1.4 0.1 4.8]
 [2.5 5.  2.  5.7]
 [2.7 3.9 1.4 5.2]
 [3.  4.2 1.2 5.7]
 [3.  5.2 2.3 6.7]
 [3.2 5.7 2.3 6.9]
 [2.8 4.6 1.5 6.5]
 [2.5 3.9 1.1 5.6]
 [2.6 4.  1.2 5.8]
 [3.2 4.8 1.8 5.9]
 [3.5 1.3 0.2 5.5]
 [2.8 4.5 1.3 5.7]
 [3.4 1.4 0.3 4.6]
 [2.8 4.9 2.  5.6]
 [3.3 1.7 0.5 5.1]
 [3.8 1.9 0.4 5.1]
 [3.  5.1 1.8 5.9]
 [2.5 5.8 1.8 6.7]
 [2.9 4.7 1.4 6.1]
 [3.1 1.5 0.1 4.9]
 [3.9 1.7 0.4 5.4]
 [3.2 4.7 1.4 7. ]
 [3.5 1.6 0.6 5. ]
 [3.  4.4 1.4 6.6]
 [3.8 6.4 2.  7.9]
 [2.5 4.9 1.5 6.3]
 [2.5 4.  1.3 5.5]
 [3.  1.1 0.1 4.3]
 [2.4 3.8 1.1 5.5]
 [2.9 4.2 1.3 5.7]
 [2.9 4.3 1.3 6.2]
 [3.2 5.9 2.3 6.8]
 [3.4 1.7 0.2 5.4]
 [3.4 1.6 0.2 4.8]
 [3.4 1.5 0.4 5.4]
 [2.7 5.1 1.6 6. ]
 [3.2 1.3 0.2 4.4]
 [3.1 1.6 0.2 4.8]
 [3.3 6.  2.5 6.3]
 [2.9 3.6 1.3 5.6]
 [3.1 4.4 1.4 6.7]
 [3.  1.6 0.2 5. ]
 [2.8 6.1 1.9 7.4]
 [3.2 1.2 0.2 5. ]
 [3.8 1.6 0.2 5.1]
 [3.  4.1 1.3 5.6]
 [2.8 4.8 1.4 6.8]
 [3.  5.9 2.1 7.1]
 [3.1 1.5 0.2 4.6]
 [2.3 4.4 1.3 6.3]
 [2.9 5.6 1.8 6.3]
 [2.7 5.3 1.9 6.4]
 [3.

In [224]:
#now building  adaboostclassifier on training sets and fitting 
classifier = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1),
    n_estimators=100
)
classifier.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                          

In [225]:
#now predicting based on x_test values
predictions = classifier.predict(X_test)
predictions

array([1, 2, 0, 2, 0, 2, 2, 2, 1, 0, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2,
       1])

In [226]:
y_test=y_test
predictions=predictions.reshape(-1,)


diff=pd.DataFrame({'Actual':y_test,'Predicted':predictions})
diff

Actual  Predicted
51        1          1
139       2          2
19        0          0
112       2          2
1         0          0
107       2          2
122       2          2
138       2          2
106       2          1
41        0          0
27        0          0
136       2          2
8         0          0
98        1          1
128       2          2
61        1          1
38        0          0
115       2          2
119       2          1
24        0          0
141       2          2
132       2          2
14        0          0
28        0          0
2         0          0
32        0          0
99        1          1
86        1          1
105       2          2
0         0          0
79        1          1
45        0          0
68        1          1
48        0          0
47        0          0
52        1          1
117       2          2
101       2          2
21        0          0
91        1          1
81        1          1
146       2          2
49        0          0
142       2          2
57        1          1

In [227]:
#  classification  report of our model
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))




              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.85      1.00      0.92        11
           2       1.00      0.88      0.94        17

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [228]:
from sklearn.metrics import mean_squared_error#calculating error of our model
mean_squared_error(diff['Actual'],diff['Predicted'])


0.044444444444444446

In [229]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

Accuracy: 0.9555555555555556


# accuracy of classifier through ada boost method =**95%**

# **Decision tree model** 

In [0]:
#importing decision tree classifier
from sklearn.tree import DecisionTreeClassifier


In [231]:
#fittting the training set into model
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [232]:

#testing the model
predict = dt.predict(X_test)
predict

array([1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2,
       1])

In [233]:
#comparing actual with prediction
y_test=y_test
predict=predict.reshape(-1,)

diff=pd.DataFrame({'Actual':y_test,'Predicted':predict})
diff

Actual  Predicted
51        1          1
139       2          2
19        0          0
112       2          2
1         0          0
107       2          2
122       2          2
138       2          2
106       2          2
41        0          0
27        0          0
136       2          2
8         0          0
98        1          1
128       2          2
61        1          1
38        0          0
115       2          2
119       2          1
24        0          0
141       2          2
132       2          2
14        0          0
28        0          0
2         0          0
32        0          0
99        1          1
86        1          1
105       2          2
0         0          0
79        1          1
45        0          0
68        1          1
48        0          0
47        0          0
52        1          1
117       2          2
101       2          2
21        0          0
91        1          1
81        1          1
146       2          2
49        0          0
142       2          2
57        1          1

In [234]:
#  classification  report of our model
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.92      1.00      0.96        11
           2       1.00      0.94      0.97        17

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [235]:
#calculating error
from sklearn.metrics import mean_squared_error
mean_squared_error(diff['Actual'],diff['Predicted'])


0.022222222222222223

In [236]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, predict))

Accuracy: 0.9777777777777777


# accuracy of classifier through Decision tree method =**93%**

# **Report**

**from the above we find the accuracy of the model is good by using ensemble method (ada boost)  then generalclassifier like  svm , decissiontree ,kNNclassifier etc**

**The differcence is small but this small differnce has its significance in some cases**

